---
    AWSTemplateFormatVersion: "2010-09-09"
    Description: A bucket for stacker to store CloudFormation templates
    Parameters:
        VPCCIDR:
            Description: CIDR block for the VPC.
            Type: String
        VPCName:
            Description: VPCName the VPC.
            Type: String
    
    Resources:
            OurVPC:
              Type: "AWS::EC2::VPC"
              Properties:
                CidrBlock: !Ref VPCCIDR
                Tags:
                  - Key: Name
                    Value: !Ref VPCName
          